// AUTO-GENERATED by scripts/emit-brand-colors.js — DO NOT EDIT BY HAND.
// Source: icons/brand-colors.json. Rerun `bun scripts/emit-brand-colors.js`
// (or a full `bun run build:windows`) to refresh after editing that file.

/// Brand splash background colour as (R, G, B) tuple in 0-255 sRGB.
///
/// Consumed by `setup::native_splash` for both the alpha-composite pass
/// (during PNG decode) and the `FillRect` surround around the mascot.
pub const SPLASH_BG_RGB: (u8, u8, u8) = (0x1a, 0x1a, 0x1a);
