// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {lineTokens} from "./fountain-tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lQQOPOOOOOP'#Cm'#CmOOOP'#Cn'#CnOOOP'#Co'#CoOOOP'#Cp'#CpOOOP'#Cq'#CqOOOP'#Cr'#CrOOOP'#Cs'#CsOOOP'#Ct'#CtOOOP'#Cu'#CuOOOP'#Cv'#CvOOOP'#Cw'#CwOOOP'#Cx'#CxOOOP'#Cy'#CyOOOP'#Cz'#CzOOOP'#C{'#C{OOOP'#DQ'#DQOOOP'#C|'#C|QQOPOOOOOP-E6z-E6z",
  stateData: "!U~OPPOQQORROSSOTTOUUOVVOWWOXXOYYOZZO[[O]]O^^O_^Or_O~O",
  goto: "!UuPPPPPPPPPPPPPPPPPvvvvvvvvvvvvvvvzPPP!QT`ObQbORcbTaOb",
  nodeNames: "⚠ TitlePageEntryTok SceneHeadingTok CharacterCueTok DialogueTok ParentheticalTok TransitionTok CenteredTok LyricTok NoteTok BoneyardTok PageBreakTok SectionTok SynopsisTok ActionTok ForcedActionTok Script TitlePageEntry SceneHeading CharacterCue Dialogue Parenthetical Transition Centered Lyric Note Boneyard PageBreak Section Synopsis Action BlankLine",
  maxTerm: 36,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [lineTokens],
  topRules: {"Script":[0,16]},
  tokenPrec: 0
})
