// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {lineTokens} from "./mangaplay-tokens.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$OQQOPOOOOOP'#Cp'#CpOOOP'#Cq'#CqOOOP'#Cr'#CrOOOP'#Cs'#CsOOOP'#Ct'#CtOOOP'#Cu'#CuOOOP'#Cv'#CvOOOP'#Cw'#CwOOOP'#Cx'#CxOOOP'#Cy'#CyOOOP'#Cz'#CzOOOP'#C{'#C{OOOP'#C|'#C|OOOP'#C}'#C}OOOP'#DO'#DOOOOP'#DP'#DPOOOP'#DQ'#DQOOOP'#DR'#DROOOP'#DW'#DWOOOP'#DS'#DSQQOPOOOOOP-E7Q-E7Q",
  stateData: "!_~OPPOQQORROSSOTTOUUOVVOWWOXXOYYOZZO[[O]]O^^O__O``OaaObSOxbO~O",
  goto: "![{PPPPPPPPPPPPPPPPPPPP||||||||||||||||||!QPPP!WTcOeQeORfeTdOe",
  nodeNames: "⚠ PageHeadingTok PanelHeadingTok CharacterCueTok ActionTok SFXTok TitleCardTok SceneHeadingTok TransitionTok NoteTok BoneyardTok CenteredTok LyricTok PageBreakTok TitlePageEntryTok CommentTok DialogueTok ParentheticalTok ForcedActionTok Script PageHeading PanelHeading CharacterCue Action SFX TitleCard SceneHeading Transition Note Boneyard Centered Lyric PageBreak TitlePageEntry Comment Dialogue Parenthetical BlankLine",
  maxTerm: 42,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "RORO",
  tokenizers: [lineTokens],
  topRules: {"Script":[0,19]},
  tokenPrec: 0
})
